library(gridExtra)
library(grid)
library(ggplot2)
library(lattice)

age <- ggplot(data = heart) + geom_bar(mapping = aes(x = age), color= "black", alpha = 0.5)+ labs(title = "Distribution of Age", x = "Age", y ="Frequency") + annotate("text", x=40, y=15, label= "p-value < 2.2e-16") 
maxrate <- ggplot(data = heart) + geom_bar(mapping = aes(x = thalach), color = "black", alpha = 0.5) + labs(title = "Distribution of Max Heart Rate", x = "Max Heart Rate", y = "Frequency")
blood <- ggplot(data = heart) + geom_bar(mapping = aes(x = trestbps), color = "black", alpha  = 0.5) + labs(title = "Distribution of Resting Blood Pressure", x = "Resting Blood Pressure (mmHg)", y = "Frequency") + annotate("text", x=120, y=30, label= "p-value < 2.2e-16") 
cholesterol <- ggplot(data = heart) + geom_bar(mapping = aes(x = chol), color = "black", alpha  = 0.5) + labs(title = "Distribution of Serum Cholestoral", x = "Serum Cholestoral (mg/dl)", y = "Frequency")
chestpain <-  ggplot(data = heart) + geom_bar(mapping = aes(x = cp), color = "black", alpha  = 0.5) + labs(title = "Distribution of Chest Pain (0 = no pain, 3 = severe pain)", x = "Chest Pain Type", y = "Frequency")
title=textGrob("Distributions using UC Irvine Heart Disease Dataset (T-Test against sideplots)", gp=gpar(fontsize = 13, fontface="bold"))
grid.arrange(age, maxrate, blood, cholesterol,chestpain, ncol = 3, top = title)
t.test(heart$age, heart$thalach)
t.test(heart$trestbps, heart$chol)
